### ISSUE TITLE
uctypes module TODO

### ISSUE THREAD

**Issue by pfalcon** [pfalcon/pycopy#14]
* [x] Allow to convert PTR object to int
* [x] Allow to assign to  PTR field - either int or another
* [x] Allow to pass PTR object properly to FFI functions - address held in PTR should be passed, not address of PTR field itself
* [x] Support of automatic field offset calculation - uctypes.calc_offsets(desc)
* [x] Add support for unions with .calc_offsets()
* [x] Add native C types: SHORT, INT, LONG, LONGLONG, unsigned variants (should alias to exact-sized types).
* [x] Add end-to-end usage example to docs
* [x] Update docs for changes above
* [x] Add ~~uctypes_helper~~ uctypeslib module to micropython-lib with convenience functions to create fields.
* [x] Add ~~uctypeslib~~ uctypeslib2 module to micropython-lib with any other functionality, starting with dumping of descriptors in readable form.
* [x] Implement OrderedDict literal in the core.
