### ISSUE TITLE
"Finishing Pycopy" TODO

### ISSUE THREAD

**Issue by pfalcon** [pfalcon/pycopy#15]
### Generic
* [x] Make sys.stdin and friends overridable
* [x] Implement (forward-port) `__slots__` support
* [x] Warnings should show file/line no. - enabled in pycopy-dev
* [ ] Add function (e.g. sys.warn()) to generate warning (with line no.) from Python code?

### Ports
* [x] Implement uos.remove for Unix port
* [x] Implement uos.rename for Unix port

### I/O
* [x] Implement usocket.timeout() for unix port: https://github.com/micropython/micropython/pull/2381#issuecomment-410400703
* [x] Finalize aspects of uselect.poll methods behavior: https://github.com/micropython/micropython/issues/1550#issuecomment-425272508
* [ ] Add userdata support for uselect.poll.register() - unix port done, [baremetal WIP, needs more testing](https://github.com/pfalcon/pycopy/search?q=I2680b9f83fe1221f3f8c1f6bf06e17e0fb4a664b&type=Commits)
* [x] Implement uio.BufferedReader
* [x] Clean uio.TextIOWrapper() behavior #11
* [x] Support non-blocking operation for `ussl` streams

### Modules
* [x] uctypes module finishing #14

### Imports
* [x] Allow to override `__import__`
* [ ] Better handling of errors during module import (remove from sys.modules)
